default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: amusement_development

test: &TEST
  <<: *default
  database: amusement_development

production:
  <<: *default
  database: amusement_production
