default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: amusement_development

test: &TEST
  <<: *default
  database: amusement_development

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>

# production:
#   <<: *default
#   database: amusement_production
#   username: amusement
#   password: <%= ENV['AMUSEMENT_DATABASE_PASSWORD'] %>
